レビュー用プルリクエスト
toshikifujiyoshi/todo-app pull request #4
Opened 2024-10-14 07:43 UTC by toshikifujiyoshi

2024-10-14 07:44 UTC, XeicuLy commented on app.vue
テスト

2024-10-14 12:05 UTC, XeicuLy requested changes

2024-10-14 12:05 UTC, XeicuLy commented on components/sidebar/index.vue
>  const firebaseConfig = {
[must]
環境変数に入れて使ったほうが良いです！
第三者から攻撃受けるので！

2024-10-14 12:05 UTC, XeicuLy commented on components/DatePicker/index.vue
[imo]
ディレクトリのファイル名が大文字なのは一般的ではないと思います！

2024-10-14 12:05 UTC, XeicuLy commented on components/DatePicker/index.vue
> +    v-if="date && typeof date === 'object'"
[imo]
template構文内で論理式を使用せず、computedで算出したほうが良いです！

2024-10-14 12:05 UTC, XeicuLy commented on components/sidebar/index.vue
> +    console.error('Error deleting todo:', error);
[must]
consoleの使用はESLintのルールで警告が出てしまっているので、一律無視するか別の方法でエラーを処理するかを検討してください！

2024-10-14 12:05 UTC, XeicuLy commented on components/sidebar/index.vue
> +    console.error('Error deleting todo:', error);
[must]
エラーメッセージが削除失敗したときのものになっています

2024-10-14 12:05 UTC, XeicuLy commented on components/sidebar/index.vue
> +    });
[ask]
この一連の成功した処理で、`isError`の値はfalseに戻さないんですか？

2024-10-14 12:05 UTC, XeicuLy commented on components/sidebar/index.vue
> +    }).then(() => {
[ask]
`.then()`必要ですか？

2024-10-14 12:05 UTC, XeicuLy commented on components/sidebar/index.vue
> +                v-model="todoTitle"
[imo]
`.lazy`を使ったほうがパフォーマンス的にもよいと思います！

2024-10-14 12:05 UTC, XeicuLy commented on pages/index.vue
> +                        "
[imo]
可読性が鬼のように下がるので、computedにまとめたほうが良いです！
基本的にtemplate構文内はViewに専念して、計算などはsetup関数内で行うようにしてください！

2024-11-20 05:56 UTC, toshikifujiyoshi commented on components/DatePicker/index.vue
修正済み

2024-11-20 06:22 UTC, toshikifujiyoshi commented on components/sidebar/index.vue
> +    });
[ask]
タスク追加後再レンダリングされる関係で勝手にisErrrorの値がリセットされていたため影響がなかったですが、ここでisError.value = false;に戻しておいたほうがわかりやすいですよね？？

一応falseに戻しておきます！

2024-11-20 06:23 UTC, toshikifujiyoshi commented on components/sidebar/index.vue
> +    }).then(() => {
必要ないので削除しました。

2024-11-20 06:25 UTC, toshikifujiyoshi commented on components/sidebar/index.vue
> +    console.error('Error deleting todo:', error);
開発時用にコンソールを表示していたのですが、バナーでエラーを表示しているので一旦削除します。

2024-11-20 06:26 UTC, toshikifujiyoshi commented on components/sidebar/index.vue
> +    console.error('Error deleting todo:', error);
コンソールごと削除しています。

2024-11-20 06:30 UTC, toshikifujiyoshi commented on components/sidebar/index.vue
> +                v-model="todoTitle"
指摘ありがとうございます。
修正しました！

2024-11-20 06:38 UTC, toshikifujiyoshi commented on components/DatePicker/index.vue
> +    v-if="date && typeof date === 'object'"
修正済み

2025-01-02 10:50 UTC, toshikifujiyoshi commented on components/sidebar/index.vue
>  const firebaseConfig = {
修正済み

2025-01-02 10:51 UTC, merged